### PR TITLE
Twig latest version of extension so we can use localizeddate.

### PR DESCRIPTION
**Pull request by bartdc**

### CODE REVIEW

**Comment by StijnVrolijk** [comment]
@bartdc don't you need to add some config as well?

Also; your commit message could use some work. If you execute `git rebase -i HEAD~1` you can reword the commit message, afterwards you can use `git push --force` to push it to your branch.
I suggest something along the lines of
>Update Twig to 1.5.1

**Comment by bartdc** [comment]
@StijnVrolijk No that't the only thing I had to change. Following code in Twig tpl works out of the box:

Twig:
`{{ date('2018-' ~ m ~ '-01')|localizeddate('none', 'none', app.request.locale, null, "MMMM")|capitalize }}`

Result:
`Januari`

**Comment by jonasdekeukelaere** [comment]
@bartdc I think it needs to `^1.5` with the "^", otherwise an update could possible change it to 1.6.x or 2.x.x

**Comment by jonasdekeukelaere** [comment]
See #233 - apparently the lock file was already in 1.5.1, but json not set up correctly.

**Pull request closed without merging**
