### PR TITLE
Force no interaction

### PR DESCRIPTION
**Pull request by StijnVrolijk**
See the documentation for more info

### CODE REVIEW

**Comment by ohvitorino** [comment]
Won't this have any effect on supplying parameters while generating `parameters.yml`?

**Comment by StijnVrolijk** [comment]
@ohvitorino quite possibly but it's the only working solution we've found so far. 

@tijsverkoyen perhaps it's possible to only disable interactive mode when deploying?

**Comment by tijsverkoyen** [comment]
This will break the generation of parameters.yml, but I think this feature should be removed as it is not really usefull. Also see https://github.com/sumocoders/Framework/pull/155

**Comment by tijsverkoyen** [comment]
I would suggest using #155 instead of this PR.
Also see: http://lifeat.sumocoders.be/knowledge-base/capistrano/#knowledge-base__fork__issue-with-composer-enter-required-for-each-package

**Pull request closed without merging**
