### PR TITLE
Replace KnpPaginator bundle with whiteoctober/WhiteOctoberPagerfantaB…

### LINKED ISSUE #146: Change the paginator bundle
Currently, we use the KnpPaginator bundle, this is okay for simple pagination but lacks in other areas. Filters for example aren't very easy to implement.

Therefor I suggest we take a look at some other bundles for pagination.

https://github.com/whiteoctober/Pagerfanta
https://github.com/beberlei/porpaginas

I have read something about a filter implementation for KnpPaginator bundle which includes using https://github.com/lexik/LexikFormFilterBundle . We might want to check that out aswell

### PR DESCRIPTION
**Pull request by bjorvack**
fixes #146 
uses https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle

This bundle provides multiple adaptors for different data sources, the DoctrineORMAdapter uses a query builder. For more complex functionality custom adapters can be written.

### CODE REVIEW

**Comment by StijnVrolijk** [comment]
@bjorvack care to explain why you picked this bundle? Does it fix the issues we have with the KnpPaginator bundle?

**Comment by carakas** [comment]
do you think this could be a solution to use in fork as well?

**Comment by carakas** [comment]
the bundle is for symfony 2, the framework is going to 3, does that give conflicts?

**Comment by jonasdekeukelaere** [comment]
@carakas looks like symfony2 has it's own branch on that package, master (and latest tags) should work with symfony master branch

but maybe, @bjorvack can you make this based on the 6.0.0-dev branch? and create MR for that branch?

**Pull request closed without merging**
