### PR TITLE
Make it possible to add fields from the builder to a fieldset.

### PR DESCRIPTION
**Pull request by carakas**
Example implementation:
```
$builder->add(
    'fieldset',
    'fieldset',
    [
        'fieldset_class' => 'col-xs-12 col-sm-6',
        'open_row' => true,
        'legend' => 'my.fieldset.translation',
        'fields' => function (FormBuilderInterface $builder) {
            $builder
                ->add(
                    'input',
                    'text'
                );
        },
    ]
)
```

### CODE REVIEW

**Comment by WouterSioen** [comment]
Looks good to me. Maybe add an example in the example bundle too?

**Comment by tijsverkoyen** [comment]
👍 after adding an example

**Comment by tijsverkoyen** [comment]
@carakas can you add an example pls

**Comment by carakas** [comment]
example added in https://github.com/sumocoders/FrameworkExampleBundle/pull/18

**Pull request merged**
