### PR TITLE
Improving code based on scrutinizer ci feedback

### PR DESCRIPTION
**Pull request by tijsverkoyen**

### CODE REVIEW

**Comment by WouterSioen** [comment]
I guess a lot of these commits (all the reverted ones) could be squashed into the "Use ParameterBag" commit to remove them from the commit tree.

**Comment by WouterSioen** [comment]
Looks good! :shipit:

**Comment by tijsverkoyen** [comment]
You can't squash reverts :-(

**Comment by WouterSioen** [comment]
Aw, that sucks. Can't you create a new branch, cherry pick the commits you need, and merge that one instead?

**Comment by tijsverkoyen** [comment]
Will do ;-)

**Pull request closed without merging**
